export const ACTION = {
  DEPOSIT_AAVE: "DEPOSIT_AAVE",
  WITHDRAW_AAVE: "WITHDRAW_AAVE",
  BORROW_AAVE: "BORROW_AAVE",
  REPAY_AAVE: "REPAY_AAVE",
  DEPOSIT_COMPOUND: "DEPOSIT_COMPOUND",
  WITHDRAW_COMPOUND: "WITHDRAW_COMPOUND",
  BORROW_COMPOUND: "BORROW_COMPOUND",
  REPAY_COMPOUND: "REPAY_COMPOUND",
};
